#!/bin/sh
# PreToolUse[Edit|Write]: block writes to generated or cache paths.
command -v jq >/dev/null 2>&1 || exit 0
fp=$(jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0
deny() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
  exit 0
}
case "$fp" in
*/internal/server/ui/dist/*)
  deny "internal/server/ui/dist is generated by make embed from ui/dist — edit ui/src instead and rebuild (make ui embed)."
  ;;
*/.gocache/*)
  deny ".gocache/ is a gitignored local Go build cache — never edit or add files there."
  ;;
esac
exit 0
