#!/bin/sh
# PreToolUse[Edit|Write]: block writes to generated or cache paths, and keep the
# session-start handoff injection within its byte budget.
command -v jq >/dev/null 2>&1 || exit 0
payload=$(cat) || exit 0
fp=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0
project_dir=${CLAUDE_PROJECT_DIR:-.}
case "$fp" in
/*) target=$fp ;;
*) target=$project_dir/$fp ;;
esac

# Resolve `.` and `..` textually so a non-canonical spelling such as
# docs/features/../features/HANDOFF.md cannot bypass the decisions below. A Write
# target need not exist yet, so this cannot go through realpath. A relative
# result keeps a `./` prefix because the patterns below anchor on a slash.
target=$(printf '%s\n' "$target" | awk '
{
  absolute = (substr($0, 1, 1) == "/")
  n = split($0, seg, "/")
  top = 0
  for (i = 1; i <= n; i++) {
    s = seg[i]
    if (s == "" || s == ".") continue
    if (s == "..") {
      if (top > 0 && out[top] != "..") { top--; continue }
      if (absolute) continue
    }
    out[++top] = s
  }
  res = ""
  for (i = 1; i <= top; i++) res = res "/" out[i]
  print (absolute ? (res == "" ? "/" : res) : ("." res))
}')

deny() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
  exit 0
}
case "$target" in
*/internal/server/ui/dist/*)
  deny "internal/server/ui/dist is generated by make embed from ui/dist — edit ui/src instead and rebuild (make ui embed)."
  ;;
*/.gocache/*)
  deny ".gocache/ is a gitignored local Go build cache — never edit or add files there."
  ;;
esac

case "$target" in
*/docs/features/HANDOFF.md) ;;
*) exit 0 ;;
esac

# session-start.sh injects the prelude through the end of Active change. Count
# bytes in that exact slice, rather than charging the whole handoff (or BRIEFS).
slice_bytes() {
  awk '/^## /{n++; if (n == 3) exit} {print}' "$1" | wc -c | tr -d ' '
}

max_bytes=8192
before=0
[ -f "$target" ] && before=$(slice_bytes "$target")
tmp=$(mktemp "${TMPDIR:-/tmp}/guard-edit.XXXXXX") || exit 0
trap 'rm -f "$tmp"' EXIT HUP INT TERM

# Build the proposed file for Write, or apply the first Edit replacement. If a
# caller supplies neither form, leave it alone rather than interrupting it.
if printf '%s' "$payload" | jq -e '.tool_input.content != null' >/dev/null 2>&1; then
  printf '%s' "$payload" | jq -r '.tool_input.content' >"$tmp" 2>/dev/null || exit 0
elif printf '%s' "$payload" | jq -e '.tool_input.old_string != null and .tool_input.new_string != null' >/dev/null 2>&1 && [ -f "$target" ]; then
  old=$(printf '%s' "$payload" | jq -r '.tool_input.old_string' 2>/dev/null) || exit 0
  new=$(printf '%s' "$payload" | jq -r '.tool_input.new_string' 2>/dev/null) || exit 0
  replace_all=$(printf '%s' "$payload" | jq -r '.tool_input.replace_all // false' 2>/dev/null) || exit 0
  jq -Rsr --arg old "$old" --arg new "$new" --argjson replace_all "$replace_all" \
    'if $old == "" then . elif $replace_all then split($old) | join($new) else (index($old) as $i | if $i == null then . else .[:$i] + $new + .[$i + ($old|length):] end) end' \
    "$target" >"$tmp" 2>/dev/null || exit 0
else
  exit 0
fi

after=$(slice_bytes "$tmp")
# A pre-edit hook must not turn a cleanup into an interruption. Deny only a
# proposed increase that crosses the limit (or grows an already-over-limit
# slice); shrinking and unrelated edits remain non-blocking.
if [ "$after" -gt "$max_bytes" ] && [ "$after" -gt "$before" ]; then
  deny "HANDOFF's injected Current position + Active change slice would be $after bytes, over the ${max_bytes}-byte session-start budget; shorten it or archive settled state first."
fi
exit 0
